# Generated by Django 5.2 on 2025-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
